# Generated by Django 3.2.9 on 2022-01-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_ap_no', models.BigIntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('mark_attendence', models.CharField(default='absent', max_length=10)),
                ('worker_names', models.CharField(max_length=35)),
                ('worker_job_no', models.CharField(max_length=20)),
                ('mobile_worker', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='detail_of_worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_worker', models.CharField(max_length=50)),
                ('headname_worker', models.CharField(max_length=50)),
                ('address_worker', models.CharField(max_length=100)),
                ('mobile_worker', models.BigIntegerField()),
                ('addhar_worker', models.BigIntegerField()),
                ('gender_worker', models.CharField(max_length=6)),
                ('dob_worker', models.DateField()),
                ('age_worker', models.PositiveIntegerField()),
                ('image_worker', models.ImageField(upload_to='static/worker_photo')),
                ('state_worker', models.CharField(max_length=30)),
                ('distric_worker', models.CharField(max_length=30)),
                ('block_worker', models.CharField(max_length=30)),
                ('panchayat_worker', models.CharField(max_length=30)),
                ('account_worker', models.BigIntegerField()),
                ('ifsc_worker', models.CharField(max_length=11)),
                ('bank_worker', models.CharField(max_length=35)),
                ('ap_no_worker', models.BigIntegerField(unique=True)),
                ('card_no', models.CharField(default='not issued', max_length=16)),
                ('card_status', models.CharField(default='not issued', max_length=15)),
                ('verify_name', models.CharField(default='rejected due to name not matched', max_length=50)),
                ('verify_addhar', models.CharField(default='rejected due to addhar not matched', max_length=50)),
                ('verify_gender', models.CharField(default='rejected due to gender not matched', max_length=50)),
                ('verify_image', models.CharField(default='rejected due to image not matched', max_length=50)),
                ('verify_address', models.CharField(default='rejected due to address not matched', max_length=50)),
                ('verify_account', models.CharField(default='rejected due to account not matched', max_length=50)),
                ('verify_bank', models.CharField(default='rejected due to bank not matched', max_length=50)),
                ('verify_ifsc', models.CharField(default='rejected due to ifsc code not matched', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='first_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_name', models.CharField(blank=True, max_length=50, null=True)),
                ('worker_jobcard_no', models.CharField(blank=True, max_length=16, null=True)),
                ('worker_app_no', models.BigIntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='')),
                ('image14', models.ImageField(blank=True, null=True, upload_to='')),
                ('image15', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_status', models.CharField(default='not captured', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_app', models.BigIntegerField()),
                ('worker_job', models.CharField(max_length=20)),
                ('date', models.DateField(null=True)),
                ('grampanchayat', models.CharField(max_length=30)),
                ('work', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=60)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softteam.state')),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2022.32.01/01/22')),
                ('time', models.TimeField(auto_now_add=True)),
                ('mark_attendence', models.CharField(default='absent', max_length=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='softteam.detail_of_worker')),
            ],
        ),
    ]
